### ISSUE TITLE
Potential bug in Jaro

### ISSUE THREAD

**Issue by alihitawala** [kvpradap/py_stringmatching#24]
In[26]: jaro ('abc', 'a')
Out[26]: 0.7777777777777777
In[27]: jaro ('abc', 'b')
Out[27]: 0.7777777777777777
In[28]: jaro ('abc', 'c')
Out[28]: 0.0

For last also it should output 0.7777777777777777.
Expected output : 0.7777777777777777
Actual output : 0.0

**Comment by kvpradap** [comment]
Interesting. If this is a bug, then its a bug in python-levenshtein package.

**Comment by kvpradap** [comment]
I checked Jaro implementation in python Levenshtein package. There is a bug in their Jaro implementation. It has to do with the calculation of number of positions with in which the character can be considered as a match.
 
I think the expected output is different from what you mentioned. We can discuss more about it in tomorrow's meeting.

**Comment by kvpradap** [comment]
opened up bug_jaro_jarowinkler to handle this.

**Comment by kvpradap** [comment]
@alihitawala I have updated the branch with the bug fix.

According to the book and wikipedia (also, https://asecuritysite.com/forensics/simstring) , I believe that 
jaro('abc', 'b') should be 0. 

Can you use that branch and test your soft tfidf implementation?
You can copy the softfidf implementation to bug_jaro_jarowinkler branch and update the testcases

**Comment by alihitawala** [comment]
What about the softtfidf branch. I have already committed my code there.

**Comment by alihitawala** [comment]
Can we pull in the changes for soft-tfidf on the buggy Jaro and then push in the fix for Jaro? This Jaro fix will also fix the test cases if any failing? That means Jaro's merge has to wait before we pull in the pending pull request on soft-tfidf.

**Comment by kvpradap** [comment]
After thinking a bit, I would prefer this way

1) Push jaro and Jaro winkler fix
2) Update soft tfidf based on Jaro/Jaro winkler fix.
3) Pull soft tfidf impln and test cases.

The reason is soft tfidf implementation depends on Jaro. So the test cases have to be changed based on the fixed implementation.

I have pushed in Jaro and Jaro winkler fix in the master. You can pull the latest changes in the master to softtfidf branch and update the test cases.

Let me know if you have any questions.

**Comment by alihitawala** [comment]
That's also fine.

**Comment by kvpradap** [comment]
updated jaro and pushed in the changes
